name: "Generate and publish to Snapshot Repository"
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Minecraft version from the version manifest"
        required: true

jobs:
  generate-and-publish:
    name: Generate and publish for Minecraft ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    container:
      image: openjdk:16-jdk
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate and publish mappings
        run: ./gradlew publish -PminecraftVersion="${{ github.event.inputs.version }}" --stacktrace
        env:
          SNAPSHOTS_URL: ${{ secrets.SNAPSHOTS_URL }}
          SNAPSHOTS_USERNAME: ${{ secrets.SNAPSHOTS_USERNAME }}
          SNAPSHOTS_PASSWORD: ${{ secrets.SNAPSHOTS_PASSWORD }}
