name: "Generate and publish to Snapshot Repository"
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Minecraft version from the version manifest"
        required: true
      mappings:
        description: "URL to the client mappings file from the version manifest"
        required: true
      extra_args:
        description: "Extra arguments to gradle"
        required: false

jobs:
  generate-and-publish:
    runs-on: ubuntu-latest
    container:
      image: openjdk:16-jdk
      options: --user root
    steps:
      - name: Cache build and application cache
        uses: actions/cache@v2
        with:
          path: |
            ./build
            ./cache
          key: hashed-mojmap
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Generate and publish mappings
        run: ./gradlew publish -PminecraftVersion="${{ github.event.inputs.version }}" -PmappingsUrl="${{ github.event.inputs.mappings }}" ${{ github.event.inputs.extra_args }} --stacktrace
        env:
          SNAPSHOTS_URL: ${{ secrets.SNAPSHOTS_URL }}
          SNAPSHOTS_USERNAME: ${{ secrets.SNAPSHOTS_USERNAME }}
          SNAPSHOTS_PASSWORD: ${{ secrets.SNAPSHOTS_PASSWORD }}